# Taken from here
# https://github.com/Yoshie2000/PlentyChess/blob/main/.github/workflows/plenty.yml
name: Schoenemann Build & Bench
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  engine:
    name: Schoenemann Build & Bench
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows]
    
    steps:

    - name: Clone
      uses: actions/checkout@v2

    - name: Compile
      run: cd src && make EXE=Schoenemann

    - name: Bench
      run: |
        git fetch origin ${{ github.event.pull_request.head.ref }}
        git checkout FETCH_HEAD
        bench=$(git show --summary | grep -oE 'Bench: [0-9]+' | awk '{print $2}')
        cd src/
        ./Schoenemann bench > output
        real=$(grep 'Nodes: ' output | awk '{print $4}')
        if [[ "$bench" != "$real" ]]; then echo "got $real, expected $bench (real: '$(git show --summary)')" && exit 1; fi
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: Schoenemann-${{github.sha}}-neon-${{matrix.os}}
        path: src/Schoenemann